### PR TITLE
fix JSON crash, run as root properly on macOS, update Qt

### PR DESCRIPTION
**Pull request by kambala-decapitator**
- fix random JSON parser crash
- macOS: switch back to running executable through `sudo` directly with using `--askpass`. Our app is used as askpass program and presents a simple password entry dialog.
- CI: use Qt 6.7.2

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
@phunkyfish could you check if this build works better for you?

**Comment by phunkyfish** [comment]
Quits on startup:

Screenshot 2024-07-27 at 07 25 54

**Comment by chewitt** [comment]
@kambala-decapitator I downloaded the artefact, but it crashed for me. See: https://pastebin.com/raw/sp4Zf2yr

**Comment by kambala-decapitator** [comment]
Yes, that's why I moved PR to draft

**Comment by kambala-decapitator** [comment]
@chewitt @phunkyfish please check the new build, seems to run fine on my ARM. I think I also fixed strange JSON parser crash.

**Comment by phunkyfish** [comment]
Firstly, I can't repro the crash so that's definitely fixed!

------

So just launching prompts for password, but write to disk doesn't work as no permissions.

Screenshot 2024-07-30 at 21 00 33

Launching with sudo I get the same blue bar phenomenon as with a local build and still no writing to disk:

Screenshot 2024-07-30 at 20 56 32

**Comment by kambala-decapitator** [comment]
> So just launching prompts for password

are you sure? are you running with `--elevated` perhaps?

**Comment by kambala-decapitator** [comment]
@phunkyfish @chewitt fixed the drag'n'drop issue in the new build. Now password will be asked by our own dialog (again), but now it's coming from our Qt app instead of some mysterious JS script.

Screenshot 2024-08-04 at 22 31 00

**Comment by phunkyfish** [comment]
Nice, I have confirmed this runs (without a crash) and successfully writes an SD card on both my Intel mac mini and my M3 macbook, nice work!

**Comment by phunkyfish** [comment]
@kambala-decapitator, can you add the following to your improve JSON Parser commit?

```
diff --git a/jsonparser.cpp b/jsonparser.cpp
index c6f8353..99ddf3f 100644
--- a/jsonparser.cpp
+++ b/jsonparser.cpp
@@ -152,10 +152,12 @@ void JsonParser::parseAndSet(const QByteArray &data, const QString label)
                     const auto releaseItemsNode = itReleaseItems.value().toObject();

                     const auto itFile = releaseItemsNode.find("file");
-                    ReadImageName(itFile.value().toObject(), projectIndex, imagesList, projectList);
+                    if (itFile != releaseItemsNode.end())
+                        ReadImageName(itFile.value().toObject(), projectIndex, imagesList, projectList);

                     const auto itImage = releaseItemsNode.find("image");
-                    ReadImageName(itImage.value().toObject(), projectIndex, imagesList, projectList);
+                    if (itImage != releaseItemsNode.end())
+                        ReadImageName(itImage.value().toObject(), projectIndex, imagesList, projectList);

                     const auto itUbootsNode = releaseItemsNode.find("uboot");
                     if (itUbootsNode != releaseItemsNode.end())

```

**Comment by kambala-decapitator** [comment]
> can you add the following to your improve JSON Parser commit?

Will do

**Comment by kambala-decapitator** [comment]
@chewitt can be merged

**Review by phunkyfish — APPROVED** [review]
👍

**Review by chewitt — APPROVED** [review]

**Pull request merged**
