### PR TITLE
Update to QT 6.6.2, fix mac builds and update README

### PR DESCRIPTION
**Pull request by phunkyfish**

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
it's quite questionable why one needs to compile static Qt on macOS and even compile it at all when online installer provides prebuilt binaries. I don't see any specific build options there, so it should be up to the person who builds the project how to build Qt => those build instructions are completely out of scope for the project.

**Comment by phunkyfish** [comment]
> it's quite questionable why one needs to compile static Qt on macOS and even compile it at all when online installer provides prebuilt binaries. I don't see any specific build options there, so it should be up to the person who builds the project how to build Qt => those build instructions are completely out of scope for the project.

Happy to update the instructions. This was just the easiest way I found of getting everything up and running and working. I tried and failed with the online installer a few times.

**Comment by CvH** [comment]
@kambala-decapitator 
> it's quite questionable why one needs to compile static Qt

otherwise the tool is not "standalone" anymore and requires a installer
with the recent changes for QT at linux there is no good way anymore to build a static build

So it would be good (compiling qt static at windows is also a pain) to move everything to a shared build with an installer included to pull the deps.
But like usually someone needs to do it :)

**Comment by kambala-decapitator** [comment]
creating installer with cmake is trivial. Besides, I don't think you need a real installer - a simple zip would do as well.

here we're talking about macOS specifically, but the same applies to Windows. Unfortunately, have no Linux knowledge, but as discussed on Slack, Flatpak could be an option.

**Comment by phunkyfish** [comment]
For right now this PR builds and works. We can move over to a shared lib and and installer next week.

But we can merge this PR now.

**Review by CvH — APPROVED** [review]

**Pull request merged**
