### PR TITLE
[macOS] simplify restarting app as root with Apple Script

### PR DESCRIPTION
**Pull request by kambala-decapitator**
uses a very simple Apple Script to request password instead of all that JS fuss

Screenshot 2024-02-19 at 20 47 19

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
@chewitt would such approach work?

**Comment by kambala-decapitator** [comment]
turns out it's possible to show user-friendly message. What would be a good one?

Screenshot 2024-02-19 at 21 57 59

**Comment by chewitt** [comment]
IIRC we originally used a simple AppleScript applet, but then switched to JavaScript in https://github.com/LibreELEC/usb-sd-creator/pull/24 .. I guess it doesn't matter as long as it works and then we can get the app signed/notarised.

**Comment by kambala-decapitator** [comment]
> IIRC we originally used a simple AppleScript applet, but then switched to JavaScript in #24 .. I guess it doesn't matter as long as it works and then we can get the app signed/notarised.

Thanks. Then I'd go with this PR's approach.

Which message would you like to show to the users? `LEUSC requires superuser permissions.`? IMO the original message `LibreELEC USB-SD Creator wants to make changes` doesn't provide much info what its trying to do.

**Comment by chewitt** [comment]
I'd use "LEUSC requires admin permissions" .. can we accept fingerprint input for this or it has to be user/pass?

**Comment by kambala-decapitator** [comment]
> I'd use "LEUSC requires admin permissions"

ok, will adjust

> can we accept fingerprint input for this

I believe so, but my Mac mini doesn't have such ability to check

**Pull request merged**
