### PR TITLE
Add arm64 windows zlib for msvc

### PR DESCRIPTION
**Pull request by phunkyfish**
Added zlib static for ARM64 for Windows for both VS2109 and VS2022

@kambala-decapitator is this what you need?

@chewitt should support building on windows.

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
yes, fine

but I don't understand what's mingw zlib binary doing in the repo? it's available in msys2 for both Intel and ARM: https://packages.msys2.org/base/mingw-w64-zlib (see Binary Packages)

**Comment by phunkyfish** [comment]
When I was building locally I could not get it to work without adding it. I agree it should not be there, maybe just something funny about my windows set up. I’ll do a fresh install of Windows next week and figure out why it didn’t work.

**Comment by kambala-decapitator** [comment]
ubuntu? are you cross-compiling from it to windows?

**Comment by phunkyfish** [comment]
> ubuntu? are you cross-compiling from it to windows?

Apologies, meant windows, corrected comment.

**Comment by kambala-decapitator** [comment]
well, on CI it works with zlib package from msys2 (and we tested that on local machines as well). I suggest to drop zlib mingw binary from the PR as well as remove the Intel version from the repo.

**Comment by phunkyfish** [comment]
> well, on CI it works with zlib package from msys2 (and we tested that on local machines as well). I suggest to drop zlib mingw binary from the PR as well as remove the Intel version from the repo.

You mean remove just mingw x64?

**Comment by kambala-decapitator** [comment]
X64 - remove from the repo as part of this PR, arm - drop from the PR

**Comment by phunkyfish** [comment]
> X64 - remove from the repo as part of this PR, arm - drop from the PR

Why drop arm from the PR. I’m confused now, that’s the whole purpose of the PR.

**Comment by kambala-decapitator** [comment]
Arm for mingw of course. Because binary is available in msys2

**Comment by phunkyfish** [comment]
> Arm for mingw of course. Because binary is available in msys2

Gotcha, will do.

**Comment by phunkyfish** [comment]
Done

**Pull request merged**
